-- liquibase formatted sql

-- changeset Sami:1
CREATE EXTENSION IF NOT EXISTS postgis;
create sequence hibernate_sequence start 10000 increment 1;
create table admin (id int8 not null, password varchar(255), username varchar(255), primary key (id));
create table block_user (user_id int8 not null, blocker_id int8 not null);
create table city (id int8 not null, place_id varchar(255), picture_id int8, country_id int8, primary key (id));
create table city_address_config (id int8 not null, priority int4 not null, type varchar(255), city_id int8, primary key (id));
create table city_translation (id int8 not null, language varchar(255), name varchar(255), city_id int8, primary key (id));
create table confirmation_code (id int8 not null, code int4 not null, expiry timestamp, user_auth_id int8, primary key (id));
create table country (id int8 not null, code varchar(255), flag_id int8, picture_id int8, primary key (id));
create table country_address_config (id int8 not null, level varchar(255), priority int4 not null, type varchar(255), country_id int8, primary key (id));
create table country_translation (id int8 not null, language varchar(255), name varchar(255), country_id int8, primary key (id));
create table device_location (id varchar(255) not null, created_at timestamp, modified_at timestamp, point GEOMETRY, user_id int8, primary key (id));
create table favorites (id int8 not null, post_time timestamp, hotel_id int8, user_id int8, primary key (id));
create table favorites_quality (favorites_id int8 not null, quality_id int8 not null);
create table follow (follower_id int8 not null, following_id int8 not null);
create table follow_request (id int8 not null, timestamp timestamp, follower_id int8, following_id int8, primary key (id));
create table gift (id int8 not null, name varchar(255), other_info varchar(255), points int4 not null, picture_id int8, hotel_id int8, primary key (id));
create table google_auto_complete_hotel (id varchar(255) not null, address varchar(255), description varchar(255), expiry_date timestamp, name varchar(255), reference varchar(255), types bytea, primary key (id));
create table google_hotel (id varchar(255) not null, address varchar(255), created_at timestamp, expiry_date timestamp, geolat float4, geolong float4, google_map_url varchar(255), language varchar(255), name varchar(255), phone varchar(255), point GEOMETRY, status varchar(255), city_id int8, country_id int8, locality_id int8, photo_id int8, hotel_price_level_id int8, primary key (id));
create table google_hotel_address (place_id varchar(255) not null, address_components TEXT, adr_address TEXT, created_at timestamp, primary key (place_id));
create table my_region (id varchar(255) not null, geolat float4, geolong float4, point GEOMETRY, country_id int8, photo_id int8, primary key (id));
create table my_region_translation (id int8 not null, address varchar(255), language varchar(255), name varchar(255), region_id varchar(255), primary key (id));
create table my_hotels (id int8 not null, created_at timestamp, expiry_date timestamp, geolat float4, geolong float4, google_map_url varchar(255), phone varchar(255), place_id varchar(255), point GEOMETRY, status varchar(255), city_id int8, country_id int8, google_price_level_id int8, locality_id int8, photo_id int8, hotel_price_level_id int8, primary key (id));
create table my_hotels_translations (id int8 not null, address varchar(255), language varchar(255), name varchar(255), hotel_id int8, primary key (id));
create table images (id  bigserial not null, image_url varchar(255), thumbnail_url varchar(255), hotel_id int8, primary key (id));
create table language (code varchar(255) not null, image_url varchar(255), name varchar(255), primary key (code));
create table locality (id int8 not null, place_id varchar(255), picture_id int8, city_id int8, primary key (id));
create table locality_translation (id int8 not null, language varchar(255), name varchar(255), locality_id int8, primary key (id));
create table loyal_points (id int8 not null, loyalty_points int4, hotel_id int8, user_id int8, primary key (id));
create table notification (id int8 not null, created_at timestamp, text varchar(255), title varchar(255), hotel_id int8, status_id int8, user_id int8, primary key (id));
create table notification_setting (user_id int8 not null, friend_adding_wishlist boolean not null, friend_favorite boolean not null, friend_joined boolean not null, friend_status boolean not null, new_follower boolean not null, newsfeed_alert boolean not null, pause_all boolean not null, promotion_from_hotel boolean not null, primary key (user_id));
create table orders (id int8 not null, amount float8, created_at date, order_type varchar(255), points int4, updated_at date, hotel_id int8, user_id int8, primary key (id));
create table points_history (id int8 not null, points_spent int4, hotel_id int8, user_id int8, primary key (id));
create table promotion (id int8 not null, active boolean, budget int4, button_color varchar(255), button_text varchar(255), created_at timestamp, duration int4, geolat float4, geolong float4, modified_at timestamp, radius float4, region varchar(255), show_logo boolean, sub_title varchar(255), sub_title_color varchar(255), title varchar(255), title_color varchar(255), cover_id int8, hotel_id int8, primary key (id));
create table promotion_target_audience (promotion_id int8 not null, target_audience_id int8 not null);
create table qr_code (id int8 not null, redeemed boolean not null, order_id int8, hotel_id int8, primary key (id));
create table quality (id int8 not null, active boolean, equivalent_quality varchar(255), name varchar(255), quality_type_id int8, primary key (id));
create table quality_type (id int8 not null, name varchar(255), primary key (id));
create table query_autocomplete (id int8 not null, components varchar(255), expiry_date timestamp, language varchar(255), off_set varchar(255), origin varchar(255), point GEOMETRY, radius float8, session_token varchar(255), types varchar(255), user_query varchar(255), user_id int8, primary key (id));
create table query_autocomplete_response (auto_complete_query_id int8 not null, response_id varchar(255) not null);
create table query_search (id int8 not null, expiry_date timestamp, keyword varchar(255), language varchar(255), point GEOMETRY, radius float8, type varchar(255), user_id int8, primary key (id));
create table query_search_response (search_query_id int8 not null, response_id varchar(255) not null);
create table refresh_token (id  bigserial not null, created_at timestamp, token varchar(255) not null, validity_period int8 not null, user_id int8, primary key (id));
create table refresh_token_admin (id  bigserial not null, created_at timestamp, token varchar(255) not null, validity_period int8 not null, admin_id int8, primary key (id));
create table hotel_price (id int8 not null, name varchar(255), primary key (id));
create table hotel_price_config (id int8 not null, price_level_threshold float4, price_range_users int4, primary key (id));
create table hotel_price_ranges (id int8 not null, range int4 not null, hotel_id int8, user_id int8, primary key (id));
create table hotel_rank (id int8 not null, current_rank int4 not null, previous_rank int4, updated_at timestamp, hotel_id int8, primary key (id));
create table hotel_verification_appointment (id int8 not null, appointment_date timestamp, hotel_id int8, primary key (id));
create table status (id int8 not null, name varchar(255), percentage int4, primary key (id));
create table status_history (id int8 not null, created_at date, updated_at date, from_id int8, to_id int8, user_id int8, primary key (id));
create table suggestion (id int8 not null, created_at timestamp, google_hotel_id varchar(255), my_hotel_id int8, user_id int8, primary key (id));
create table target_audience (id int8 not null, title varchar(255), primary key (id));
create table user_auths (id int8 not null, apple_id varchar(255), email varchar(255), facebook_id varchar(255), google_id varchar(255), password varchar(255), phone varchar(255), type varchar(255), verified boolean, user_id int8, primary key (id));
create table user_device_token (id int8 not null, device_token varchar(255), user_id int8, primary key (id));
create table users (id int8 not null, bio TEXT, dob date, first_name varchar(255), is_blocked boolean, is_chef boolean, is_claimed boolean, is_pending_chef boolean, is_private boolean, language varchar(255), last_name varchar(255), nick_name varchar(255), point GEOMETRY, timezone_id varchar(255), user_type varchar(255), country_id int8, photo_id int8, primary key (id));
create table users_notification (id int8 not null, status varchar(255), notification_id int8, user_id int8, primary key (id));
create table users_promotion (user_id int8 not null, promotion_id int8 not null);
create table users_status (user_id int8 not null, status_id int8 not null);
create table wishlists (id int8 not null, context varchar(255), created_at timestamp, hotel_id int8, user_id int8, primary key (id));
alter table refresh_token add constraint UK_r4k4edos30bx9neoq81mdvwph unique (token);
alter table refresh_token_admin add constraint UK_pn7146nxbwxieg1k4lwxr3xtt unique (token);
alter table block_user add constraint FKo0fwph1cknbix01dgl90r8udh foreign key (blocker_id) references users;
alter table block_user add constraint FKh5mn70c14j9qgigvnbuqwspub foreign key (user_id) references users;
alter table city add constraint FKd33o4109jgk3ru8p13nfabirk foreign key (picture_id) references images;
alter table city add constraint FKrpd7j1p7yxr784adkx4pyepba foreign key (country_id) references country;
alter table city_address_config add constraint FKrw3afibknqrk5i0hgc30icob3 foreign key (city_id) references city;
alter table city_translation add constraint FK8mo2romxbv6b5e20uyo9te5bi foreign key (city_id) references city;
alter table confirmation_code add constraint FKjctrgcgiesw3juippalc76cnf foreign key (user_auth_id) references user_auths;
alter table country add constraint FKae2gpjgerns3rrmlvbd2a668j foreign key (flag_id) references images;
alter table country add constraint FKqmyvek2ceriy7xujn53n6t2y0 foreign key (picture_id) references images;
alter table country_address_config add constraint FK7aex98wwnri7v6vh96lv328v9 foreign key (country_id) references country;
alter table country_translation add constraint FKpqmitn8i8ghcttxskjj1dy7ms foreign key (country_id) references country;
alter table device_location add constraint FK43cxaywukij6ctj9vhnna04ue foreign key (user_id) references users;
alter table favorites add constraint FK1vrcpa8gm81phux2typp4tg2a foreign key (hotel_id) references my_hotels;
alter table favorites add constraint FKk7du8b8ewipawnnpg76d55fus foreign key (user_id) references users;
alter table favorites_quality add constraint FKikjhjg36cj9om9pn4i6i5el81 foreign key (quality_id) references quality;
alter table favorites_quality add constraint FK65akn95tv9pcfi99a1x20l8eu foreign key (favorites_id) references favorites;
alter table follow add constraint FK9oqsjovu9bl95dwt8ibiy2oey foreign key (following_id) references users;
alter table follow add constraint FKjikg34txcxnhcky26w14fvfcc foreign key (follower_id) references users;
alter table follow_request add constraint FK8lk5n2kb4ovgd1smpdu3f6dyb foreign key (follower_id) references users;
alter table follow_request add constraint FKnkynfauorusxtg44ou6mcb1d9 foreign key (following_id) references users;
alter table gift add constraint FK3v9sqnmr9ku2ljgqhawi35tj6 foreign key (picture_id) references images;
alter table gift add constraint FKbxg2nr3xgkoa5r5rlitcboyhl foreign key (hotel_id) references my_hotels;
alter table google_hotel add constraint FKa1i87tdja958hplu02itl2057 foreign key (city_id) references city;
alter table google_hotel add constraint FKm7wdagc352bik153tonysu61g foreign key (country_id) references country;
alter table google_hotel add constraint FK3w81q23jbei4e2vvafppbp0qr foreign key (locality_id) references locality;
alter table google_hotel add constraint FKrxo2ebmbff8oblug75yv8upva foreign key (photo_id) references images;
alter table google_hotel add constraint FK2rqh17txn6gf4fiya8ohhnu7q foreign key (hotel_price_level_id) references hotel_price;
alter table my_region add constraint FK5stmqx0dkwu2dxj6dv26awgs4 foreign key (country_id) references country;
alter table my_region add constraint FKjob1fygh1yx6gvr7vg0h7iq9v foreign key (photo_id) references images;
alter table my_region_translation add constraint FKesyskp8tjkl8ni1epry3vuasi foreign key (region_id) references my_region;
alter table my_hotels add constraint FKrbwc9060178hdb13to52lrsh2 foreign key (city_id) references city;
alter table my_hotels add constraint FKbvi0mii657nev2a30jmqya7lk foreign key (country_id) references country;
alter table my_hotels add constraint FKagusjlnttcqjiwb7iuivgkijo foreign key (google_price_level_id) references hotel_price;
alter table my_hotels add constraint FKb28takgs5pyxwu1r9mw9te8ti foreign key (locality_id) references locality;
alter table my_hotels add constraint FKnvni819xs17hhjc61fj7ef6pp foreign key (photo_id) references images;
alter table my_hotels add constraint FKnidw6puq4gy86jaxg84cmdlx6 foreign key (hotel_price_level_id) references hotel_price;
alter table my_hotels_translations add constraint FKpuo32q3l5r0mmgkq05oey8vbg foreign key (hotel_id) references my_hotels;
alter table images add constraint FKbbygdlky1t81c6tvsi7axy48g foreign key (hotel_id) references my_hotels;
alter table locality add constraint FKn86ymbjuh6hro250txab39nvu foreign key (picture_id) references images;
alter table locality add constraint FKp1syf1rn75wb35xcjfbx8fbgs foreign key (city_id) references city;
alter table locality_translation add constraint FK1fq6elhi6dtfgqq7icxvbkvxx foreign key (locality_id) references locality;
alter table loyal_points add constraint FK3oko4c9daybesuik22hiwbdti foreign key (hotel_id) references my_hotels;
alter table loyal_points add constraint FKad3b9uk385q7u57ebec0icqaf foreign key (user_id) references users;
alter table notification add constraint FKfkfeaxtayoin4mu73n7s5onfd foreign key (hotel_id) references my_hotels;
alter table notification add constraint FK5tak5s7d8v964omfb11iogqun foreign key (status_id) references status;
alter table notification add constraint FKnk4ftb5am9ubmkv1661h15ds9 foreign key (user_id) references users;
alter table notification_setting add constraint FKmk226jk5f6j26wg7moshwhdx8 foreign key (user_id) references users;
alter table orders add constraint FKos4xrltyjrkht9exsdgbgt366 foreign key (hotel_id) references my_hotels;
alter table orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users;
alter table points_history add constraint FKh0vyuo6shuvd316e8b1i4lpil foreign key (hotel_id) references my_hotels;
alter table points_history add constraint FKqixq59hvpoinedepk2hourhws foreign key (user_id) references users;
alter table promotion add constraint FKnl4san9cndwad9wkw3ayksisc foreign key (cover_id) references images;
alter table promotion add constraint FKf09vmyo9o6yy8nbdhixp9jdq8 foreign key (hotel_id) references my_hotels;
alter table promotion_target_audience add constraint FKd6kp539l7gxdw5xycfrom2xtb foreign key (target_audience_id) references target_audience;
alter table promotion_target_audience add constraint FK1nf4yd9wg3924aqyg1ncji2s foreign key (promotion_id) references promotion;
alter table qr_code add constraint FKbw0x2r1qx44hix3k7w1bqmee foreign key (order_id) references orders;
alter table qr_code add constraint FKhsccc6uv67xtfjwrnbpye588p foreign key (hotel_id) references my_hotels;
alter table quality add constraint FKn4yiwuxbxcoffylwbt7rnsxge foreign key (quality_type_id) references quality_type;
alter table query_autocomplete add constraint FKljp8y10c1jd77srgvb4mrlm0k foreign key (user_id) references users;
alter table query_autocomplete_response add constraint FKf5ce21ret3q49ubbhw3dydc2y foreign key (response_id) references google_auto_complete_hotel;
alter table query_autocomplete_response add constraint FKdl3yp2f2ja58v93rfkbuytos0 foreign key (auto_complete_query_id) references query_autocomplete;
alter table query_search add constraint FKfmmj9lhfdahauj8op135vgvke foreign key (user_id) references users;
alter table query_search_response add constraint FKj2s1w6185m6p6k9oguxrdu91m foreign key (response_id) references google_hotel;
alter table query_search_response add constraint FK16ht5hqjitsjjjjjmfq1hefoh foreign key (search_query_id) references query_search;
alter table refresh_token add constraint FKjtx87i0jvq2svedphegvdwcuy foreign key (user_id) references users;
alter table refresh_token_admin add constraint FKo4mvphvkpkqocxul2lov7nh04 foreign key (admin_id) references admin;
alter table hotel_price_ranges add constraint FKm23iubkh2wsjlun2n76f1ej37 foreign key (hotel_id) references my_hotels;
alter table hotel_price_ranges add constraint FK81m5695bxmqx1mek00eqo0o4k foreign key (user_id) references users;
alter table hotel_rank add constraint FKlx7x9nqeat84vix1fo0jwi3n5 foreign key (hotel_id) references my_hotels;
alter table hotel_verification_appointment add constraint FK1ng1hapn0ufv3dtvcb8m6jlg6 foreign key (hotel_id) references my_hotels;
alter table status_history add constraint FK6reoylaeabsndshwggdceu4hr foreign key (from_id) references status;
alter table status_history add constraint FKh3iha3ayqpab53op5ahns7r0b foreign key (to_id) references status;
alter table status_history add constraint FKdsmrp5c3iqtfsllmrmtt52djv foreign key (user_id) references users;
alter table suggestion add constraint FKb7pqcnvspggwsrf9n4gibu2sc foreign key (google_hotel_id) references google_hotel;
alter table suggestion add constraint FKrkr3ht7ja3ay3nc65o174g76s foreign key (my_hotel_id) references my_hotels;
alter table suggestion add constraint FKlwyt2aya9jw90lwo4wt6edstj foreign key (user_id) references users;
alter table user_auths add constraint FKl35o65ovs04mariyxjj10ack1 foreign key (user_id) references users;
alter table user_device_token add constraint FKmxrps4u6j1deghwlf4lhpd2g0 foreign key (user_id) references users;
alter table users add constraint FK5t4yyo3f0ctxayh7voqv51fmg foreign key (country_id) references country;
alter table users add constraint FKok0x1qf7gr9plkgk6folocj9n foreign key (photo_id) references images;
alter table users_notification add constraint FKe1uu9oe6hxf3xqit4o44rjxvj foreign key (notification_id) references notification;
alter table users_notification add constraint FK3rypl6jxyo2r0gno07o3jedb4 foreign key (user_id) references users;
alter table users_promotion add constraint FKot8rj09aptyk8he6an09our3v foreign key (promotion_id) references promotion;
alter table users_promotion add constraint FKt7lsle9grc73u8lyn75g6digj foreign key (user_id) references users;
alter table users_status add constraint FKkxwuo069uuur6dolfusu7d5og foreign key (status_id) references status;
alter table users_status add constraint FKsh94fsos58gq2g28maty4brrh foreign key (user_id) references users;
alter table wishlists add constraint FKcxq0whexufqkq1v196tn2oh18 foreign key (hotel_id) references my_hotels;
alter table wishlists add constraint FK330pyw2el06fn5g28ypyljt16 foreign key (user_id) references users;
